name: Main

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Get tag
        id: tag
        run: echo "tag=$(date +%s)" >> "$GITHUB_OUTPUT"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mrtenz/vsftpd:${{ steps.tag.outputs.tag }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Publish the Docker image
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin && docker push mrtenz/vsftpd:${{ needs.build.outputs.tag }}
