name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mrtenz/vsftpd:latest --tag mrtenz/vsftpd:${{ github.ref_name }}
      - name: Push the Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push mrtenz/vsftpd:latest
          docker push mrtenz/vsftpd:${{ github.ref_name }}
